<!DOCTYPE html>
<html>

<head>
    <title>Laporan Kesehatan Mental</title>
    <style>
        body {
            font-family: sans-serif;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 10px;
        }

        .header h1 {
            color: #4f46e5;
            margin: 0;
        }

        .header p {
            margin: 5px 0;
            color: #666;
            font-size: 12px;
        }

        .meta-info {
            margin-bottom: 20px;
        }

        .meta-info table {
            width: 100%;
        }

        .meta-info td {
            padding: 5px;
        }

        .label {
            font-weight: bold;
            color: #555;
        }

        h2 {
            font-size: 16px;
            border-left: 5px solid #4f46e5;
            padding-left: 10px;
            margin-top: 30px;
            background: #f3f4f6;
            padding: 8px;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 12px;
        }

        table.data th {
            background-color: #4f46e5;
            color: white;
            padding: 8px;
            text-align: left;
        }

        table.data td {
            border-bottom: 1px solid #ddd;
            padding: 8px;
        }

        table.data tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .badge {
            padding: 3px 8px;
            border-radius: 10px;
            font-size: 10px;
            color: white;
            font-weight: bold;
        }

        .bg-positif {
            background-color: #10b981;
        }

        .bg-negatif {
            background-color: #ef4444;
        }

        .bg-netral {
            background-color: #6b7280;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #aaa;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>Health-AI Report</h1>
        <p>Laporan Monitoring Kesehatan Mental Pribadi</p>
        <p>Generated by AI System • {{ now()->format('d M Y H:i') }}</p>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label" width="100">Nama User</td>
                <td>: {{ Auth::user()->name }}</td>
                <td class="label" width="100">Email</td>
                <td>: {{ Auth::user()->email }}</td>
            </tr>
            <tr>
                <td class="label">Periode</td>
                <td>: {{ now()->translatedFormat('F Y') }}</td>
                <td class="label">Total Entry</td>
                <td>: {{ $moods->count() + $journals->count() }} Data</td>
            </tr>
        </table>
    </div>

    <h2>1. Riwayat Mood (Emosi Harian)</h2>
    @if($moods->count() > 0)
        <table class="data">
            <thead>
                <tr>
                    <th width="20%">Tanggal</th>
                    <th width="15%">Level</th>
                    <th width="25%">Faktor</th>
                    <th>Catatan</th>
                </tr>
            </thead>
            <tbody>
                @foreach($moods as $m)
                    @php
                        $labels = [1 => 'Buruk 😭', 2 => 'Sedih 😢', 3 => 'Biasa 😐', 4 => 'Baik 🙂', 5 => 'Hebat 🤩'];
                    @endphp
                    <tr>
                        <td>{{ $m->created_at->format('d/m/Y H:i') }}</td>
                        <td>{{ $labels[$m->emoji_level] }}</td>
                        <td>{{ $m->tags ?? '-' }}</td>
                        <td>{{ $m->description ?? '-' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="color: #888; font-style: italic;">Tidak ada data mood bulan ini.</p>
    @endif

    <h2>2. Analisis Jurnal & Sentimen</h2>
    @if($journals->count() > 0)
        <table class="data">
            <thead>
                <tr>
                    <th width="20%">Tanggal</th>
                    <th width="30%">Judul</th>
                    <th width="10%">Sentimen</th>
                    <th>Ringkasan AI</th>
                </tr>
            </thead>
            <tbody>
                @foreach($journals as $j)
                    <tr>
                        <td>{{ $j->created_at->format('d/m/Y') }}</td>
                        <td>{{ $j->title }}</td>
                        <td>
                            @php
                                $color = match ($j->detected_sentiment) {
                                    'Positif' => 'bg-positif',
                                    'Negatif' => 'bg-negatif',
                                    default => 'bg-netral',
                                };
                            @endphp
                            <span class="badge {{ $color }}">{{ $j->detected_sentiment }}</span>
                        </td>
                        <td>{{ $j->ai_summary }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="color: #888; font-style: italic;">Tidak ada jurnal bulan ini.</p>
    @endif

    <div class="footer">
        Dokumen ini dibuat otomatis oleh komputer dan sah tanpa tanda tangan basah.<br>
        Health-AI Mental Wellness System © {{ date('Y') }}
    </div>

</body>

</html>